version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = ["**/generated.go"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

[analyzers.meta]
import_root = "github.com/RobBrazier/readflow"
