# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - task generate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: binary

dockers:
  - image_templates:
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - packaging/entrypoint.sh
  - image_templates:
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
    extra_files:
      - packaging/entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/robbrazier/readflow:{{.Version}}"
    image_templates:
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-amd64"
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/robbrazier/readflow:v{{.Major}}"
    image_templates:
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-amd64"
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/robbrazier/readflow:latest"
    image_templates:
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-amd64"
      - "ghcr.io/robbrazier/readflow:{{ .Version }}-arm64v8"

# nfpms:
#   - package_name: readflow
#     vendor: Rob Brazier
#     homepage: https://github.com/RobBrazier/readflow
#     maintainer: Rob Brazier <2453018+RobBrazier@users.noreply.github.com>
#     description: Track your Kobo reads on Anilist.co and Hardcover.app using Calibre-Web and Calibre databases
#     formats:
#       - deb
#       - rpm
#     bindir: /usr/local/bin
#     contents:
#       - src: ./packaging/systemd/readflow.timer
#         dst: /usr/lib/systemd/system/readflow.timer
#         type: config
#         file_info:
#           mode: 0644
#       - src: ./packaging/systemd/readflow.service
#         dst: /usr/lib/systemd/system/readflow.service
#         type: config
#         file_info:
#           mode: 0644
#
#     scripts:
#       postinstall: packaging/scripts/postinstall.sh
#       postremove: packaging/scripts/postremove.sh

changelog:
  use: github-native
  filters:
    exclude:
      - "^docs(\\(.*\\))?:"
      - "^test(\\(.*\\))?:"
      - "^chore(\\(.*\\))?:"
