version: "3"

dotenv:
  - .env

tasks:
  default:
    silent: true
    cmd: task --list-all

  build:
    deps:
      - generate
    env:
      CGO_ENABLED: 0
    cmd: go build -o readflow main.go

  generate:
    vars:
      GENQLIENT_VERSION:
        sh: grep -m 1 genqlient go.mod | awk '{ print $2 }'
    cmds:
      - go get github.com/Khan/genqlient@{{ .GENQLIENT_VERSION }}
      - defer: go mod tidy
      - go generate ./...

  test:
    cmd: go test ./...

  download-schemas:
    cmds:
      - "gquil introspection generate-sdl https://graphql.anilist.co > schemas/anilist/schema.gql"
      - "gquil introspection generate-sdl https://api.hardcover.app/v1/graphql -H 'Authorization: {{ .HARDCOVER_TOKEN }}' > schemas/hardcover/schema.gql"
    requires:
      vars: [HARDCOVER_TOKEN]
