version: "3"

tasks:
  build:
    deps:
      - generate
    cmd: go build -o readflow main.go

  generate:
    cmd: go generate ./...

  test:
    cmd: go test ./...

  download-schemas:
    cmds:
      - "npx -y gql-sdl https://graphql.anilist.co -o schemas/anilist/schema.gql"
      - "npx -y gql-sdl https://api.hardcover.app/v1/graphql -o schemas/hardcover/schema.gql -H 'Authorization: {{ .HARDCOVER_TOKEN }}'"
    requires:
      vars: [HARDCOVER_TOKEN]
