version: "3"

tasks:
  build:
    deps:
      - generate
    cmd: go build -o readflow main.go

  generate:
    cmd: go generate ./...

  test:
    cmd: go test ./...

  download-schemas:
    cmds:
      - go run github.com/suessflorian/gqlfetch/gqlfetch@latest --endpoint https://graphql.anilist.co > schemas/anilist/schema.gql
      - go run github.com/suessflorian/gqlfetch/gqlfetch@latest --endpoint https://api.hardcover.app/v1/graphql --header "Authorization={{ .HARDCOVER_TOKEN }}" | sed 's/""""/"""/g' > schemas/hardcover/schema.gql
