query GetCurrentUser {
  Viewer {
    id
    name
  }
}


query GetUserMediaById($mediaId: Int) {
  Media(id: $mediaId, type: MANGA) {
    volumes
    chapters
    mediaListEntry {
      progressVolumes
      progress
      status
    }
    title {
      userPreferred
    }
  }
}
