fragment MediaEntry on Media {
  volumes
  chapters
  mediaListEntry {
    progressVolumes
    progress
    status
  }
  title {
    userPreferred
  }
}

query GetCurrentUser {
  Viewer {
    id
    name
  }
}


query GetUserMediaById($mediaId: Int) {
  Media(id: $mediaId, type: MANGA) {
    ...MediaEntry
  }
}

query GetUserMediaByIds($mediaIds: [Int]) {
  Page {
    media(id_in: $mediaIds) {
      ...MediaEntry
    }
  }
}
