fragment MediaListEntry on MediaList {
  progressVolumes
  progress
  status
}

fragment MediaTitle on MediaTitle {
  userPreferred
}

fragment MediaEntry on Media {
  id
  volumes
  chapters
  mediaListEntry {
    ...MediaListEntry
  }
  title {
    ...MediaTitle
  }
}

query GetUserMediaById($mediaId: Int) {
  Media(id: $mediaId, type: MANGA) {
    ...MediaEntry
  }
}

query GetUserMediaByIds($mediaIds: [Int]) {
  Page {
    media(id_in: $mediaIds) {
      ...MediaEntry
    }
  }
}
