mutation CreateUserBook($bookId: Int!, $status: Int, $editionId: Int) {
  insert_user_book(object: {book_id: $bookId, status_id: $status, edition_id: $editionId}) {
    id
    error
    user_book {
      user_book_reads {
        ...UserBookReads
      }
    }
  }
}

mutation ChangeBookStatus($userBookId: Int!, $status: Int) {
  update_user_book(id: $userBookId, object: {status_id: $status}) {
    id
    error
  }
}

mutation UpdateBookProgress($id: Int!, $pages: Int, $editionId: Int, $startedAt: date) {
  update_user_book_read(id: $id, object: {
    progress_pages: $pages,
    edition_id: $editionId,
    started_at: $startedAt,
  }) {
    id
    error
  }
}

mutation FinishBookProgress($id: Int!, $pages: Int, $editionId: Int, $startedAt: date, $finishedAt: date) {
  update_user_book_read(id: $id, object: {
    progress_pages: $pages,
    edition_id: $editionId,
    started_at: $startedAt,
    finished_at: $finishedAt,
  }) {
    id
    error
  }
}
