query GetBookReviews {
  me {
    user_books(
      where: { _and: [ 
        {has_review: {_eq: true}},
        {status_id: {_eq: 3 }}
      ]}
      order_by: [
        { date_added: desc },
        { reviewed_at: desc }
      ]
    ) {
      reviewed_at
      date_added
      review_raw
      rating
      book {
        title
      }
    }
  }
}

query GetCurrentUser {
  me {
    name
    username
  }
}

query FindBookByName($title: String) {
  books(
    where: {title: {_regex: $title}}
    order_by: {users_read_count: desc_nulls_last}
  ) {
    title
    slug
    users_read_count
    contributions {
      author {
        name
      }
    }
    release_date
    book_series {
      series {
        name
      }
    }
    taggings {
      tag {
        tag
      }
    }
    image {
      url
    }
    editions {
      asin
      isbn_13
      isbn_10
      title
    }
    description
  }
}


query FindBookBySlug($slug: String) {
  books(
    where: {slug: {_eq: $slug}}
    order_by: {users_read_count: desc_nulls_last}
  ) {
    title
    slug
    users_read_count
    contributions {
      author {
        name
      }
    }
    release_date
    book_series {
      series {
        name
      }
    }
    taggings {
      tag {
        tag
      }
    }
    image {
      url
    }
    editions {
      asin
      isbn_13
      isbn_10
      title
    }
    description
  }
}
