query GetCurrentUser {
  me {
    name
    username
  }
}

query GetUserBooksBySlug($slug: String) {
  me {
    user_books(where: {book: {slug: {_eq: $slug}}}) {
      status_id
      book_id
      book {
        slug
        title
      }
      edition {
        id
        pages
      }
      user_book_reads(order_by: {started_at: desc}, limit: 1) {
        id
        progress
        progress_pages
        started_at
        finished_at
        edition {
          id
          pages
        }
      }
    }
  }
}
